CREATE DATABASE IFPR_BIBLIOTECA;

use IFPR_BIBLIOTECA;
CREATE TABLE BOOKS(
    ID INT PRIMARY KEY,
    TITULO VARCHAR(50),
    AUTOR VARCHAR(50),
    ANO INT,
    QRCODE VARCHAR(500),
    LOCALIZACAO VARCHAR(150),
    STATUS CHAR(1)
);

INSERT INTO BOOKS 
       (TITULO, AUTOR, ANO, QRCODE, LOCALIZACAO, STATUS) 
VALUES(?, ?, ?, ?, ?, ?);


UPDATE BOOKS SET TITULO = ?
                 AUTOR  = ?,
                 ANO    = ?,
                 QRCODE = ?,
                 LOCALIZACAO = ?,
                 STATUS = ?
 WHERE ID = ?;


 CREATE TABLE USUARIO(
    ID_USUARIO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME_USUARIO VARCHAR(100) NOT NULL,
    SENHA_USUARIO VARCHAR(100) NOT NULL,
    EMAIL_USUARIO VARCHAR(100) NOT NULL,
    DATANASCIMENTO_USUARIO DATE NOT NULL,
    IDADE_USUARIO INT NOT NULL,
    ENDERECO_USUARIO VARCHAR(150)
);                   


CREATE TABLE EMPRESTADO(
    ID_EMPRESTADO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_LIVRO INT DEFAULT 0,
    ID_USUARIO INT DEFAULT 0,
    DATA_EMPRESTADO DATE NOT NULL,
    DATA_DEVOLUCAO_EMPRESTADO DATE NOT NULL,
    STATUS_EMPRESTIMO ENUM('EMPRESTADO','DEVOLVIDO') DEFAULT 'EMPRESTADO',
    FOREIGN KEY (ID_LIVRO) REFERENCES BOOKS(ID),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);